name: Build Sudoku Editor Plus

on: workflow_dispatch

jobs:
  build-sudoku-editor-plus:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - uses: actions/checkout@v4
      with:
        ref: build
        path: repo-build
    - name: Set up output directory
      run: |
        cd ${{ github.workspace }}/repo-build
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        mkdir -p build-outputs
        rm -rf build-outputs/sudoku-editor
        git add .
    - name: Setup build environment
      run: |
        # Update Rust
        rustup update

        # Setup Emscripten environment
        rustup target add wasm32-unknown-emscripten
        cd ${{ runner.temp }}
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: Clone common repositories
      run: |
        git clone https://github.com/semiexp/cspuz_core.git --recursive ${{ runner.temp }}/cspuz_core
        git clone https://github.com/semiexp/third-party-licenses.git ${{ runner.temp }}/third-party-licenses
    - name: Build Sudoku Editor Plus
      run: |
        source ${{ runner.temp }}/emsdk/emsdk_env.sh

        # Clone sudoku-editor-plus
        git clone https://github.com/semiexp/sudoku-editor.git ${{ runner.temp }}/sudoku-editor

        export REVISION_SUDOKU_EDITOR=`cd ${{ runner.temp }}/sudoku-editor && git rev-parse HEAD`
        export REVISION_CSPUZ_CORE=`cd ${{ runner.temp }}/cspuz_core && git rev-parse HEAD`

        # Prepare index.html
        python3 ${{ github.workspace }}/main/prepare_index_html.py \
          --title "Sudoku Editor Plus" \
          --out ${{ runner.temp }}/sudoku-editor/index.html \
          --meta \
            revision-sudoku-editor $REVISION_SUDOKU_EDITOR \
            revision-cspuz-core $REVISION_CSPUZ_CORE

        # Build sudoku-editor
        cd ${{ runner.temp }}/sudoku-editor
        npm install

        python3 ${{ runner.temp }}/third-party-licenses/collect.py \
          -o ${{ runner.temp }}/sudoku-editor/public/licenses.txt \
          ${{ runner.temp }}/sudoku-editor \
          ${{ runner.temp }}/cspuz_core

        npm run build-solver
        npm run build

        # Copy build outputs
        cp -r ${{ runner.temp }}/sudoku-editor/dist/ ${{ github.workspace }}/repo-build/build-outputs/sudoku-editor
    - name: Commit
      run: |
        cd ${{ github.workspace }}/repo-build
        git add .
        git commit -m "Update Sudoku Editor Plus"
        git push origin build
