name: Deploy apps

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build repository
      run: |
        # we manually clone apps-dev so that we can share build-outputs in dev and prod environments
        git clone -b build https://github.com/semiexp/apps-dev.git ${{ runner.temp }}/apps-dev-build
    - name: Copy files
      run: |
        mkdir -p ${{ runner.temp }}/build-outputs
        cp -r ${{ runner.temp }}/apps-dev-build/build-outputs/* ${{ runner.temp }}/build-outputs
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ runner.temp }}/build-outputs
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
