name: Deploy apps

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: build
    - name: Copy files
      run: |
        mkdir -p ${{ runner.temp }}/build-outputs
        cp -r ${{ github.workspace }}/build-outputs/* ${{ runner.temp }}/build-outputs
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ runner.temp }}/build-outputs
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
